language:
    - cpp

matrix:
  include:
    # linux with gcc 8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      dist: trusty
      compiler: gcc

before_install:
  - eval "${MATRIX_EVAL}"

script:
    - CC=gcc make test

 
