language:
    - cpp

matrix:
  include:
    # linux with gcc 8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      dist: trusty
      compiler: gcc

before_install:
  - eval "${MATRIX_EVAL}"
#  - sudo apt-get install python2-dev       libasound2-dev       libjack-jackd2-dev     libsamplerate-dev       liblrdf-dev       libsndfile-dev      ladspa-sdk      glib2-dev      calf-plugins      binutils-dev      libc6-dev      tk8.5 libogg-dev libvorbis-dev libspeex-dev fftw-dev fftw3-dev guile libxkbfile-dev xorg-x11-util-macros cmake libfreetype6-dev libxinerama-dev libxcursor-dev libxrandr-dev libqtwebkit-dev llvm-dev libboost-all-dev libssl-dev ncurses-dev libxcb-keysyms1-dev qt5-dev qt5webkit-dev qt5x11extras-dev qt5-qttools-static-dev qtbase5-private-dev gmp-dev mpfr-dev libmpc-dev

script:
    - sudo apt-get qt5-dev
    - make common/keyboard_sub_ids.h
    - CC=gcc make test

#    - make packages
#    - BUILDTYPE=DEBUG ./build_linux.sh -j `nproc`

 
